issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - errcheck
    - unused
  enable:
    - errorlint
    - goimports
    - govet
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/prometheus/promu
